services:
  - type: web
    name: matchai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: matchai
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://matchaibackend.onrender.com
    routes:
      # spa, every path serves index.html
      - type: rewrite
        source: /*
        destination: /index.html
